add: signIn functionality
SimplyTechnologies/ios-internship-2024 pull request #5
Opened 2024-10-22 12:23 UTC by iskandaryansona

-email and pass validation
-create ui screen

2024-10-22 12:31 UTC, pmuradian commented on Birthday/Birthday/Modules/SignIn/ViewModel/SignInViewModel.swift
> +    func setButton() {
misleading naming, please rename

2024-10-22 12:37 UTC, pmuradian commented on Birthday/Birthday/Modules/SignIn/View/SignInView.swift
too many empty lines in this file

2024-10-22 12:52 UTC, AkselAvetisyan commented on Birthday/Birthday/Modules/SignIn/View/SignInView.swift
> +
Remove additional spaces

2024-10-22 12:52 UTC, AkselAvetisyan commented on Birthday/Birthday/Modules/SignIn/View/SignInView.swift
> +    var body: some View {
Add spacings here also

2024-10-22 12:52 UTC, AkselAvetisyan commented on Birthday/Birthday/Modules/SignIn/View/SignInView.swift
> +private struct SignInFields: View {
No need to make separate object if it is not going to be reused, better to have computed property.

2024-10-22 12:52 UTC, AkselAvetisyan commented on Birthday/Birthday/Modules/SignIn/ViewModel/SignInViewModel.swift
> +    func checkEmail(){
Make separate file for validations or write it in string extension as this validation can be used in registration, user profile, etc.

2024-10-22 12:52 UTC, AkselAvetisyan commented on Birthday/Birthday/Utils/Extensions/Extension + View/ValidationTextField.swift
> +                Group {
Please avoid from additional view wrapping, `Group` is odd here.

2024-10-22 12:52 UTC, AkselAvetisyan commented on Birthday/Birthday/Utils/Extensions/Extension + View/ValidationTextField.swift
> +    let placeholder: String
Please make attention to access controls.

2024-10-22 12:53 UTC, AkselAvetisyan commented
@iskandaryansona Make attention to styling guides, here are couple of issues that need to be fixed.

2024-10-23 07:09 UTC, iskandaryansona commented
Uploading Screen Recording 2024-10-23 at 11.06.29.mov…

2024-10-23 07:10 UTC, iskandaryansona commented
https://github.com/user-attachments/assets/f80466a4-bb71-4082-a7fd-5258ac6333fd

2024-10-23 07:25 UTC, nellyAslanyan commented on Birthday/Birthday/Modules/SignIn/View/SignInView.swift
> +    @StateObject private var viewModel = SignInViewModel()
can be let, and better approach is to inject this

2024-10-23 07:27 UTC, nellyAslanyan commented on Birthday/Birthday/Screens/ContentView.swift
> +        SignInView()
please discard this, as landing view is going to be here

2024-10-23 07:29 UTC, nellyAslanyan commented
Add space before {

2024-10-23 07:34 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/Shape/EnabledButton.swift
> +struct EnabledButton: ButtonStyle {
Lets make is more reusable, PrimaryButtonStyle Sind better, you can use Environment isEnabled property, this will be more native, and this button style should handle press state too

2024-10-23 07:34 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/Extension + View/ValidationTextField.swift
> +                .placeholder(when: inputText.isEmpty) {Text(placeholder)}
add spaces in {} part

2024-10-23 07:34 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/Extension + View/ValidationTextField.swift
> +//#Preview {
can't we have this preview?

2024-10-23 07:36 UTC, nellyAslanyan commented on Birthday/Birthday/Modules/SignIn/ViewModel/SignInViewModel.swift
> +import SwiftUI
do you need this import?

2024-10-23 10:10 UTC, Aslanyan99n commented on Birthday/Birthday/Modules/SignIn/View/SignInView.swift
> +                VStack(spacing: 20.0){
Sona jan please add space before {

2024-10-23 10:10 UTC, Aslanyan99n commented on Birthday/Birthday/Modules/SignIn/View/SignInView.swift
> +                                    inputText: $viewModel.email,
Please change localized string place.

2024-10-23 10:10 UTC, Aslanyan99n commented on Birthday/Birthday/Modules/SignIn/View/SignInView.swift
> +                                    inputText: $viewModel.password,
This also

2024-10-23 10:10 UTC, Aslanyan99n commented on Birthday/Birthday/Modules/SignIn/View/SignInView.swift
> +            .font(.system(size: 20, design: .default).weight(.bold))
Please change all localized string

2024-10-23 10:10 UTC, Aslanyan99n commented on Birthday/Birthday/Modules/SignIn/View/SignInView.swift
> +    let isEnabled: Bool
Add space between property and structure

2024-10-23 10:10 UTC, Aslanyan99n commented on Birthday/Birthday/Modules/SignIn/View/SignInView.swift
> +    }
Add space

2024-10-23 10:10 UTC, Aslanyan99n commented on Birthday/Birthday/Modules/SignIn/View/SignInView.swift
> +
Please remove blank line

2024-10-23 10:10 UTC, Aslanyan99n commented on Birthday/Birthday/Modules/SignIn/ViewModel/SignInViewModel.swift
> +    @Published var passErrorText:String = ""
Please add space after : for all properties

2024-10-23 10:10 UTC, Aslanyan99n commented on Birthday/Birthday/Utils/Extensions/Extension + View/Extension + View.swift
> +    func placeholder<Content: View>(
Add blank line for all extensions

2024-10-23 13:16 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/Extension + View/ValidationTextField.swift
> +    init(placeholder: String, inputText: Binding<String>, errorText: String = "", isPasswordHidden: Binding<Bool>, isSecure: Bool = false) {
multiline style here

2024-10-23 13:17 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/Texts.swift
> +  enum Label{
empty line here

2024-10-23 13:17 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/Texts.swift
>    }
and here

2024-10-23 13:18 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/String+Ext.swift
> +    func isEmailValid() -> Bool{
empty space here

2024-10-23 13:19 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/String+Ext.swift
> +    func isPassValid() -> Bool{
and here

2024-10-23 13:19 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/Extension + View/Extension + View.swift
> +    func textFieldStyle() -> some View {
empty line here

2024-10-23 13:19 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/Extension + View/Extension + View.swift
> +    }
and here

2024-10-23 13:20 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/String+Ext.swift
> +extension String{
and here

2024-10-23 13:21 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/Texts.swift
> +  enum TextField{
empty space here

2024-10-23 13:23 UTC, mikael-martirosyan commented on Birthday/Birthday/Utils/Extensions/Shape/EnabledButton.swift
> +      .foregroundColor(configuration.isPressed ? .darkRed : (isDisable ? .mainPink : .darkRed))
I believe it would be better to separate the color selection by moving the ternary operator from here to a function or a computed property

2024-10-23 13:24 UTC, mikael-martirosyan commented on Birthday/Birthday/Utils/Extensions/Shape/EnabledButton.swift
> +      .background(configuration.isPressed ? .mainPink : (isDisable ? .darkRed : .mainPink))
The same

2024-10-23 14:44 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/Extension + View/CustomNavBarModifier.swift
> +        Color.lightPink.ignoresSafeArea()
indentation issue here

2024-10-23 14:44 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/Extension + View/ValidationTextField.swift
> +  init(placeholder: String,
first property should be on new line, and ) closing brace too

2024-10-23 14:46 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/String+Ext.swift
> +extension String {
please add new Neil's pin this file

2024-10-23 14:46 UTC, nellyAslanyan commented on Birthday/Birthday/Utils/Extensions/Extension + View/Extension + View.swift
> +extension View {
please add new Neil's pin this file

2024-10-23 15:17 UTC, AkselAvetisyan approved these changes

2024-10-23 15:17 UTC, AkselAvetisyan reviewed
.

2024-10-23 15:18 UTC, AkselAvetisyan requested changes
.

2024-10-23 15:32 UTC, AkselAvetisyan approved these changes

2024-10-23 15:33 UTC, merged